<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Jds.$(MSBuildProjectName)</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.20"/>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.Testing" Version="8.10.0"/>
    <PackageReference Include="TUnit" Version="1.11.45" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\example-console\NiceNotice.Tests.ExampleConsoleApp.csproj"/>
    <ProjectReference Include="..\example-webapi\NiceNotice.Tests.ExampleWebApi.csproj"/>
    <ProjectReference Include="..\unit\NiceNotice.Aws.Sns.Tests.Unit.csproj"/>
  </ItemGroup>

</Project>
